-- require "user.colorscheme.tokyo-night"
require "user.colorscheme.vscode"
-- require "user.colorscheme.neon"
-- require "user.colorscheme.abstract-cs"
-- require "user.colorscheme.material"
-- require "user.colorscheme.nord"
-- require "user.colorscheme.ayu"
-- require "user.colorscheme.default-good"
