require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.colorscheme"
require "user.cmp"
require "user.LSP"
require "user.treesitter"
require "user.nvim-comment"
require "user.nvim-lastplace"
require "user.lualine"
require "user.alpha"
require "user.autopairs"
require "user.telescope"

